name: JDK 17

on:
  push:
    branches: 
     - master
     - 17
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: 
     - master
     - 17
  schedule:
    - cron: '10 0 28 2,3,6,9,11,12 *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  jdk-17:
    name: oracle
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Push to Docker Hub(Oracle)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: 17/Dockerfile
          push: true
          tags: |
            buzzxu/java:17
            ghcr.io/buzzxu/java:17
  openjdk-17:
    name: openjdk
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push(Corretto)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: 17/corretto/Dockerfile
          push: true
          tags: |
            buzzxu/java:17-openjdk
            ghcr.io/buzzxu/java:17-openjdk
      - 
        name: Build and push(Zulu)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: 17/zulu/Dockerfile
          push: true
          tags: |
            buzzxu/java:17-zulu
            ghcr.io/buzzxu/java:17-zulu
      - 
        name: Build and push(Adoptium-alpine)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: 17/alpine/Dockerfile
          push: true
          tags: |
            buzzxu/java:17-alpine
            ghcr.io/buzzxu/java:17-alpine
      - 
        name: Build and push(OpenJ9)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: 17/openj9/Dockerfile
          push: true
          tags: |
            buzzxu/java:17-openj9
            ghcr.io/buzzxu/java:17-openj9
      - 
        name: Build and push(TencentKona)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: 17/kona/Dockerfile
          push: true
          tags: |
            buzzxu/java:17-kona
            ghcr.io/buzzxu/java:17-kona
      - 
        name: Build and push(Dragonwell)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: 17/dragonwell/Dockerfile
          push: true
          tags: |
            buzzxu/java:17-dragonwell
            ghcr.io/buzzxu/java:17-dragonwell