name: JDK 17

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  jdk-17:
    name: java-17
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: 17/Dockerfile
          push: true
          tags: buzzxu/java:17
      - 
        name: Push to Github packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: 17/Dockerfile
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}/java:17